-- 合同历史段落语义识别服务 - Oracle 11g 初始化脚本
-- 本脚本只创建第一版核心业务所需的一张历史段落表、一个序列和一个检索索引。

CREATE TABLE TPIF_HTDLYB (
    ID              NUMBER(19)      NOT NULL,
    YWBW            CLOB            NOT NULL,
    GFBW            CLOB            NOT NULL,
    TEXT_HASH       VARCHAR2(64)    NOT NULL,
    BGLX_CODES      VARCHAR2(4000)  NOT NULL,
    VECTOR_DATA     BLOB            NOT NULL,
    VECTOR_DIM      NUMBER(10)      NOT NULL,
    MODEL_VERSION   VARCHAR2(100)   NOT NULL,
    SOURCE_FILE     VARCHAR2(500),
    SFSX            NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATE_TIME     DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TPIF_HTDLYB PRIMARY KEY (ID),
    CONSTRAINT UK_TPIF_HTDLYB_HASH UNIQUE (TEXT_HASH)
);

CREATE SEQUENCE SEQ_TPIF_HTDLYB START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX IDX_HTDLYB_MODEL
    ON TPIF_HTDLYB(MODEL_VERSION, VECTOR_DIM, SFSX);

COMMIT;
