-- 合同历史段落语义识别服务 - Oracle 11g 初始化脚本
-- 本脚本只创建第一版核心业务所需的一张历史段落表、一个序列和一个检索索引。

CREATE TABLE TPIF_HTDLYB (
    ID              NUMBER(19)      NOT NULL,
    YWBW            CLOB            NOT NULL,
    GFBW            CLOB            NOT NULL,
    TEXT_HASH       VARCHAR2(64)    NOT NULL,
    BGLX_CODES      VARCHAR2(4000)  NOT NULL,
    VECTOR_DATA     BLOB            NOT NULL,
    VECTOR_DIM      NUMBER(10)      NOT NULL,
    MODEL_VERSION   VARCHAR2(100)   NOT NULL,
    SOURCE_FILE     VARCHAR2(500),
    SFSX            NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATE_TIME     DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TPIF_HTDLYB PRIMARY KEY (ID),
    CONSTRAINT UK_TPIF_HTDLYB_HASH UNIQUE (TEXT_HASH)
);

COMMENT ON TABLE TPIF_HTDLYB IS '合同历史段落与变更类型语义检索样本表';

COMMENT ON COLUMN TPIF_HTDLYB.ID IS '主键ID，由SEQ_TPIF_HTDLYB序列生成';
COMMENT ON COLUMN TPIF_HTDLYB.YWBW IS 'Excel导入的原始合同段落文本';
COMMENT ON COLUMN TPIF_HTDLYB.GFBW IS '规范化后的合同段落，用于文本Hash计算和向量生成';
COMMENT ON COLUMN TPIF_HTDLYB.TEXT_HASH IS '规范化段落的SHA-256十六进制值，用于去重和精确匹配';
COMMENT ON COLUMN TPIF_HTDLYB.BGLX_CODES IS '段落对应的变更类型编码，去重排序后以英文分号分隔';
COMMENT ON COLUMN TPIF_HTDLYB.VECTOR_DATA IS 'L2归一化后的Float32小端序语义向量BLOB';
COMMENT ON COLUMN TPIF_HTDLYB.VECTOR_DIM IS '语义向量维度，由模型版本和应用配置共同确定，当前使用1024维';
COMMENT ON COLUMN TPIF_HTDLYB.MODEL_VERSION IS '生成语义向量的模型版本，不同版本向量禁止混合检索';
COMMENT ON COLUMN TPIF_HTDLYB.SOURCE_FILE IS '历史样本导入来源Excel文件名';
COMMENT ON COLUMN TPIF_HTDLYB.SFSX IS '是否参与检索：1-生效，0-停用';
COMMENT ON COLUMN TPIF_HTDLYB.CREATE_TIME IS '历史样本创建时间';

-- 历史样本主键序列。
CREATE SEQUENCE SEQ_TPIF_HTDLYB START WITH 1 INCREMENT BY 1 NOCACHE;

-- 按模型版本、向量维度和生效状态加载内存索引时使用。
CREATE INDEX IDX_HTDLYB_MODEL
    ON TPIF_HTDLYB(MODEL_VERSION, VECTOR_DIM, SFSX);

COMMIT;
