-- /compare 分析留痕增量脚本。
-- 三张表由应用短事务保证一致性，不建立物理外键，便于日志归档和独立清理。

CREATE TABLE HT_ANALYSIS_LOG (
    ID                      NUMBER(19)      NOT NULL,
    ANALYSIS_ID             VARCHAR2(64)    NOT NULL,
    INST_ID                 NUMBER(19)      NOT NULL,
    USER_ID                 VARCHAR2(100)   NOT NULL,
    ANALYSIS_TYPE           VARCHAR2(50)    NOT NULL,
    OLD_FILE_GET_PATH       VARCHAR2(1000),
    NEW_FILE_GET_PATH       VARCHAR2(1000),
    CHANGE_FILE_GET_PATH    VARCHAR2(1000),
    STATUS                  VARCHAR2(30)    NOT NULL,
    CHANGED_PARAGRAPH_COUNT NUMBER(10),
    CHANGE_TYPE_CODES       VARCHAR2(4000),
    EMBEDDING_MODEL         VARCHAR2(200),
    MODEL_VERSION           VARCHAR2(100),
    TOTAL_COST_MS           NUMBER(19),
    COMPARE_COST_MS         NUMBER(19),
    PREDICT_COST_MS         NUMBER(19),
    ERROR_MESSAGE           CLOB,
    RESULT_JSON             CLOB,
    CREATE_TIME             DATE DEFAULT SYSDATE NOT NULL,
    FINISH_TIME             DATE,
    CONSTRAINT PK_HT_ANALYSIS_LOG PRIMARY KEY (ID),
    CONSTRAINT UK_HT_ANALYSIS_LOG_AID UNIQUE (ANALYSIS_ID),
    CONSTRAINT CK_HT_ANALYSIS_LOG_STATUS CHECK (
        STATUS IN ('PROCESSING', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED'))
);

CREATE SEQUENCE SEQ_HT_ANALYSIS_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_HT_ANALYSIS_LOG_INST ON HT_ANALYSIS_LOG(INST_ID);
CREATE INDEX IDX_HT_ANALYSIS_LOG_USER ON HT_ANALYSIS_LOG(USER_ID);
CREATE INDEX IDX_HT_ANALYSIS_LOG_STATUS ON HT_ANALYSIS_LOG(STATUS, CREATE_TIME);

COMMENT ON TABLE HT_ANALYSIS_LOG IS '合同变更分析任务主记录及完整结果快照';
COMMENT ON COLUMN HT_ANALYSIS_LOG.ID IS '主键ID，由SEQ_HT_ANALYSIS_LOG序列生成';
COMMENT ON COLUMN HT_ANALYSIS_LOG.ANALYSIS_ID IS '一次/compare分析的唯一业务标识';
COMMENT ON COLUMN HT_ANALYSIS_LOG.INST_ID IS '流程实例ID，仅用于业务关联和追踪';
COMMENT ON COLUMN HT_ANALYSIS_LOG.USER_ID IS '本次分析关联的操作用户';
COMMENT ON COLUMN HT_ANALYSIS_LOG.ANALYSIS_TYPE IS '分析类型：DOUBLE_VERSION-双版本比对，CHANGE_DOCUMENT-单份变更文件分析';
COMMENT ON COLUMN HT_ANALYSIS_LOG.OLD_FILE_GET_PATH IS '双版本比对的旧版合同文件获取路径';
COMMENT ON COLUMN HT_ANALYSIS_LOG.NEW_FILE_GET_PATH IS '双版本比对的新版合同文件获取路径';
COMMENT ON COLUMN HT_ANALYSIS_LOG.CHANGE_FILE_GET_PATH IS '单文件分析的变更文件获取路径';
COMMENT ON COLUMN HT_ANALYSIS_LOG.STATUS IS '分析状态：PROCESSING、SUCCESS、PARTIAL_SUCCESS或FAILED';
COMMENT ON COLUMN HT_ANALYSIS_LOG.CHANGED_PARAGRAPH_COUNT IS '识别到的变化段落总数';
COMMENT ON COLUMN HT_ANALYSIS_LOG.CHANGE_TYPE_CODES IS '文档级最终变更类型编码，英文分号分隔';
COMMENT ON COLUMN HT_ANALYSIS_LOG.EMBEDDING_MODEL IS '调用Embedding网关时使用的模型名称';
COMMENT ON COLUMN HT_ANALYSIS_LOG.MODEL_VERSION IS '历史向量检索使用的模型版本';
COMMENT ON COLUMN HT_ANALYSIS_LOG.TOTAL_COST_MS IS '本次分析总耗时，单位毫秒';
COMMENT ON COLUMN HT_ANALYSIS_LOG.COMPARE_COST_MS IS '文档比对与变化提取耗时，单位毫秒';
COMMENT ON COLUMN HT_ANALYSIS_LOG.PREDICT_COST_MS IS '段落向量识别与文档级聚合耗时，单位毫秒';
COMMENT ON COLUMN HT_ANALYSIS_LOG.ERROR_MESSAGE IS '分析失败时记录的错误信息';
COMMENT ON COLUMN HT_ANALYSIS_LOG.RESULT_JSON IS '未裁剪的完整ContractCompareResponse JSON快照';
COMMENT ON COLUMN HT_ANALYSIS_LOG.CREATE_TIME IS '分析任务创建时间';
COMMENT ON COLUMN HT_ANALYSIS_LOG.FINISH_TIME IS '分析任务完成或失败时间';

CREATE TABLE HT_ANALYSIS_PARA_LOG (
    ID                NUMBER(19)      NOT NULL,
    ANALYSIS_ID       VARCHAR2(64)    NOT NULL,
    PARAGRAPH_ID      VARCHAR2(100)   NOT NULL,
    CLAUSE_NO         VARCHAR2(200),
    CLAUSE_TITLE      VARCHAR2(1000),
    PARENT_CLAUSE_NO  VARCHAR2(200),
    SOURCE_HEADING    VARCHAR2(2000),
    TARGET_CLAUSE_REFERENCE VARCHAR2(1000),
    CHANGE_TYPE       VARCHAR2(30),
    OLD_CONTENT       CLOB,
    NEW_CONTENT       CLOB,
    PREDICTION_TEXT   CLOB,
    PREDICTION_STATUS VARCHAR2(50),
    INPUT_SCOPE       VARCHAR2(50),
    CHANGE_TYPE_CODES VARCHAR2(4000),
    MAX_SIMILARITY    NUMBER(10,6),
    MATCH_TYPE        VARCHAR2(50),
    FALLBACK_USED     NUMBER(1) DEFAULT 0 NOT NULL,
    CREATE_TIME       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_HT_ANALYSIS_PARA_LOG PRIMARY KEY (ID),
    CONSTRAINT UK_HT_ANALYSIS_PARA_AID_PID UNIQUE (ANALYSIS_ID, PARAGRAPH_ID),
    CONSTRAINT CK_HT_ANALYSIS_PARA_FALLBACK CHECK (FALLBACK_USED IN (0, 1))
);

CREATE SEQUENCE SEQ_HT_ANALYSIS_PARA_LOG START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON TABLE HT_ANALYSIS_PARA_LOG IS '合同变更分析的变化段落及预测检索字段';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.ID IS '主键ID，由SEQ_HT_ANALYSIS_PARA_LOG序列生成';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.ANALYSIS_ID IS '与HT_ANALYSIS_LOG逻辑关联，不建物理外键';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.PARAGRAPH_ID IS '本次分析内变化段落的唯一标识';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.CLAUSE_NO IS '变化段落所属条款编号';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.CLAUSE_TITLE IS '变化段落所属条款标题';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.PARENT_CLAUSE_NO IS '变化段落所属上级条款编号';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.SOURCE_HEADING IS '单文件变更来源标题';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.TARGET_CLAUSE_REFERENCE IS '单文件变更指向的目标条款';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.CHANGE_TYPE IS '段落变化类型：ADDED、MODIFIED或DELETED';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.OLD_CONTENT IS '变化前的段落内容';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.NEW_CONTENT IS '变化后的段落内容';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.PREDICTION_TEXT IS '首轮识别的基础段落文本，新增修改取新段落，删除取旧段落';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.PREDICTION_STATUS IS '段落预测状态，如MATCHED、NO_RELIABLE_MATCH、FAILED或SKIPPED_TOO_LONG';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.INPUT_SCOPE IS '实际识别范围：NEW_PARAGRAPH、OLD_PARAGRAPH、NEW_CONTEXT或OLD_CONTEXT';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.CHANGE_TYPE_CODES IS '段落预测的变更类型编码，英文分号分隔';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.MAX_SIMILARITY IS '实际识别输入与Top-K历史样本的最高余弦相似度';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.MATCH_TYPE IS '历史样本匹配类型：EXACT、SEMANTIC或NO_RELIABLE_MATCH';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.FALLBACK_USED IS '是否使用上下文兜底：1是，0否';
COMMENT ON COLUMN HT_ANALYSIS_PARA_LOG.CREATE_TIME IS '变化段落记录创建时间';

CREATE TABLE HT_ANALYSIS_MATCH_LOG (
    ID                   NUMBER(19)      NOT NULL,
    ANALYSIS_ID          VARCHAR2(64)    NOT NULL,
    PARAGRAPH_LOG_ID     NUMBER(19)      NOT NULL,
    HISTORICAL_SAMPLE_ID NUMBER(19)      NOT NULL,
    SIMILARITY           NUMBER(10,6),
    CHANGE_TYPE_CODES    VARCHAR2(4000),
    RANK_NO              NUMBER(10)      NOT NULL,
    CREATE_TIME          DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_HT_ANALYSIS_MATCH_LOG PRIMARY KEY (ID),
    CONSTRAINT UK_HT_ANALYSIS_MATCH_RANK UNIQUE (PARAGRAPH_LOG_ID, RANK_NO),
    CONSTRAINT CK_HT_ANALYSIS_MATCH_RANK CHECK (RANK_NO > 0)
);

CREATE SEQUENCE SEQ_HT_ANALYSIS_MATCH_LOG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_HT_ANALYSIS_MATCH_AID ON HT_ANALYSIS_MATCH_LOG(ANALYSIS_ID);

COMMENT ON TABLE HT_ANALYSIS_MATCH_LOG IS '合同变更分析段落匹配的历史Top-K证据';
COMMENT ON COLUMN HT_ANALYSIS_MATCH_LOG.ID IS '主键ID，由SEQ_HT_ANALYSIS_MATCH_LOG序列生成';
COMMENT ON COLUMN HT_ANALYSIS_MATCH_LOG.ANALYSIS_ID IS '与HT_ANALYSIS_LOG逻辑关联，不建物理外键';
COMMENT ON COLUMN HT_ANALYSIS_MATCH_LOG.PARAGRAPH_LOG_ID IS '与HT_ANALYSIS_PARA_LOG逻辑关联，不建物理外键';
COMMENT ON COLUMN HT_ANALYSIS_MATCH_LOG.HISTORICAL_SAMPLE_ID IS '历史样本可失效或清理，因此不建立物理外键';
COMMENT ON COLUMN HT_ANALYSIS_MATCH_LOG.SIMILARITY IS '实际识别输入与该历史样本的余弦相似度';
COMMENT ON COLUMN HT_ANALYSIS_MATCH_LOG.CHANGE_TYPE_CODES IS '该历史样本关联的变更类型编码，英文分号分隔';
COMMENT ON COLUMN HT_ANALYSIS_MATCH_LOG.RANK_NO IS '该历史样本在段落Top-K匹配中的排名，从1开始';
COMMENT ON COLUMN HT_ANALYSIS_MATCH_LOG.CREATE_TIME IS '历史样本匹配证据创建时间';

COMMIT;
