-- /compare 分析日志回滚（先删明细再删主表；三表之间无数据库外键）。
DROP TABLE HT_ANALYSIS_MATCH_LOG PURGE;
DROP SEQUENCE SEQ_HT_ANALYSIS_MATCH_LOG;
DROP TABLE HT_ANALYSIS_PARA_LOG PURGE;
DROP SEQUENCE SEQ_HT_ANALYSIS_PARA_LOG;
DROP TABLE HT_ANALYSIS_LOG PURGE;
DROP SEQUENCE SEQ_HT_ANALYSIS_LOG;
